/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.newAccount;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Role.SupplierRole;
import Business.Supplier.Supplier;
import Business.Labour.SkilledLabour;
import Business.Labour.DeliveryPerson;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Organization.DeliveryLabourOrganization;
import Business.Organization.SkilledLabourOrganization;
import Business.Organization.SupplierOrganization;
import Business.Role.CustomerRole;
import Business.Role.DeliveryRole;
import Business.Role.SkilledLabourRole;
import Business.UserAccount.UserAccount;
import UserInterface.SystemAdminRole.NetworkRequestPanel;
import UserInterface.SystemAdminRole.SysAdminWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nitin
 */
public class NewAccountWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewCustomerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;

    public NewAccountWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populate();
    }

    public void populate() {

        for (Network n : system.getNetworkList()) {
            DBoxCty.addItem(n);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        addLine1Field = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        stateField = new javax.swing.JTextField();
        addLine2Field = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        pinField = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        createButton = new javax.swing.JButton();
        DBoxCty = new javax.swing.JComboBox();
        cityField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DBoxAccount = new javax.swing.JComboBox<>();

        jLabel1.setText("Name:");

        jLabel2.setText("User Name:");

        jLabel3.setText("Password:");

        jLabel4.setText("Address Line 1:");

        jLabel5.setText("Address Line 2:");

        jLabel6.setText("City:");

        jLabel7.setText("State:");

        jLabel8.setText("Pin Code:");

        jLabel9.setText("Phone N0:");

        jLabel10.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Please Enter your details ");

        createButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/newAccount/people.png"))); // NOI18N
        createButton.setText("   Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cityField.setEditable(false);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/newAccount/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel11.setText("OR--> Enter a New City:");

        jLabel12.setText("Enter Account Type:");

        DBoxAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Supplier", "Skilled Labour", "Delivery Person" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(DBoxAccount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(stateField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(pinField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(txtPassword)
                                            .addComponent(addLine1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(createButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(phoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(addLine2Field, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(DBoxCty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnBack)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel10)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(DBoxAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addLine1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addLine2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DBoxCty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        try {
            String userName = txtUsername.getText();
            String password = txtPassword.getText();
            String name = txtName.getText();
            String add1 = addLine1Field.getText();
            String add2 = addLine2Field.getText();
            String city = cityField.getText();
            String state = stateField.getText();
            String pin = pinField.getText();
            String phone = phoneField.getText();

            if (!((userName.equals("") || (password.equals("") || (name.equals("") || (add1.equals("") || (state.equals("")))))))) {
                if (EcoSystem.checkIfUsernameIsUnique(userName)) {

                    Network n = (Network) DBoxCty.getSelectedItem();
                    String accType = (String) DBoxAccount.getSelectedItem();

                    if (accType.equals("Supplier")) {
                        SupplierOrganization so = n.getSupplierOrganization();
                        Supplier sup = so.addSupplier(name);
                        UserAccount ua = so.getUserAccountDirectory().createUserAccount(userName, password, new SupplierRole());
                        sup.setAdd1(add1);
                        sup.setAdd2(add2);
                        sup.setCity(n.getCityName());
                        sup.setPhone(phone);
                        sup.setState(state);
                        sup.setUa(ua);
                        sup.setZip(pin);
                    } else if (accType.equals("Customer")) {
                        CustomerOrganization co = n.getCustomerOrganization();
                        Customer cus = co.getCd().addCustomerDetails();
                        UserAccount ua = co.getUserAccountDirectory().createUserAccount(userName, password, new CustomerRole());
                        cus.setCustomerName(name);
                        cus.setAddress(add1);
                        cus.setContact(Double.parseDouble(phone));
                        cus.setUa(ua);
                        //cus.se
                    } else if (accType.equals("Skilled Labour")) {
                        SkilledLabourOrganization so = n.getSkilledOrganization();
                        SkilledLabour sup = so.getSkilledLabourDirectory().addSkilledLabour();
                        UserAccount ua = so.getUserAccountDirectory().createUserAccount(userName, password, new SkilledLabourRole());
                        sup.setAdd1(add1);
                        sup.setAdd2(add2);
                        sup.setCity(n.getCityName());
                        sup.setPhone(phone);
                        sup.setState(state);
                        sup.setUa(ua);
                        sup.setZip(pin);
                    } else if (accType.equals("Delivery Person")) {
                        DeliveryLabourOrganization delo = n.getDeliveryOrganization();
                        DeliveryPerson sup = delo.getDpd().addDeliveryPerson();
                        UserAccount ua = delo.getUserAccountDirectory().createUserAccount(userName, password, new DeliveryRole());
                        sup.setAdd1(add1);
                        sup.setAdd2(add2);
                        sup.setCity(n.getCityName());
                        sup.setPhone(phone);
                        sup.setState(state);
                        sup.setUa(ua);
                        sup.setZip(pin);
                    }

                    JOptionPane.showMessageDialog(null, "Account successfully created!!", "Warning", JOptionPane.WARNING_MESSAGE);

                    userProcessContainer.remove(this);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.previous(userProcessContainer);

                } else {
                    JOptionPane.showMessageDialog(null, "Please enter unique username", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "The fields marked in '*' are compulsory and can not be left blank", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter details correctly!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_createButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DBoxAccount;
    private javax.swing.JComboBox DBoxCty;
    private javax.swing.JTextField addLine1Field;
    private javax.swing.JTextField addLine2Field;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField cityField;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField pinField;
    private javax.swing.JTextField stateField;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
