/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DeliveryRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Network.Network;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.DeliveryLabourOrganization;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nitin
 */
public class DeliveryWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Network network;
    private DeliveryLabourOrganization org;
    
    
    public DeliveryWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.network = network;
        this.org = network.getDeliveryOrganization();
        populate();
    }

    void populate() {
        DefaultTableModel dtm = (DefaultTableModel) requestTable.getModel();
        dtm.setRowCount(0);

        for (OrderWorkRequest w : org.getWorkQueue().getOrderWorkQueue()) {
            for (OrderItem o : w.getOrder().getOrderItemList()) {

                Object row[] = new Object[7];

                
                row[3] = o;
                row[4] = o.getQuantity();
                row[0] = w.getCustomer();
                row[2] = w.getCustomer().getContact();
                row[1] = w.getCustomer().getAddress();
                row[5] = w.getStatus();
                row[6] = w.getMessage();
                dtm.addRow(row);
                

            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer's Name", "Address", "Phone Number", "Product Name", "Quantity", "Status", "Assigned To"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);
        if (requestTable.getColumnModel().getColumnCount() > 0) {
            requestTable.getColumnModel().getColumn(0).setResizable(false);
            requestTable.getColumnModel().getColumn(1).setResizable(false);
            requestTable.getColumnModel().getColumn(2).setResizable(false);
            requestTable.getColumnModel().getColumn(3).setResizable(false);
            requestTable.getColumnModel().getColumn(4).setResizable(false);
            requestTable.getColumnModel().getColumn(5).setResizable(false);
            requestTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jButton2.setText("Assign To Me");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnComplete))
                .addContainerGap(520, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int selectedRow = requestTable.getSelectedRow();
    

        if (selectedRow >= 0) {
            OrderItem orderItem = (OrderItem) requestTable.getValueAt(selectedRow, 3);
            
            
            for (OrderWorkRequest w : org.getWorkQueue().getOrderWorkQueue()) {
            for (OrderItem o : w.getOrder().getOrderItemList()) {
                if(!w.getMessage().equals("Complete")){
                    
                if(o.equals(orderItem)){
                    w.setMessage("Assigned to :" + account.getUsername());
                    populate();
                    break;
                }
            }
                else{
                    JOptionPane.showMessageDialog(null, "Request already completed!");
                }
            }
            populate();
        }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Request!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
int selectedRow = requestTable.getSelectedRow();
    

        if (selectedRow >= 0) {
            OrderItem orderItem = (OrderItem) requestTable.getValueAt(selectedRow, 3);
            
            
            for (OrderWorkRequest w : org.getWorkQueue().getOrderWorkQueue()) {
            for (OrderItem o : w.getOrder().getOrderItemList()) {
                if(o.equals(orderItem)){
                if(!w.getMessage().equals("Complete")){
                    w.setMessage("Delivered! Completed by :" + account.getUsername());
                    w.setStatus("Complete");
                    populate();
                    break;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Request already completed!");
                }
                }
                
            }
            populate();
        }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Request!");
        }
    }//GEN-LAST:event_btnCompleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables
}
