/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PartyEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Dell-Smart
 */
public class AdminTasksPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminTasksPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    Network network;
    Enterprise enterprise;
    UserAccount account;

    public AdminTasksPanel(JPanel userProcessContainer, EcoSystem system, Enterprise enterprise, Network network, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        this.network = network;
        this.account = account;
         populate();
    }

   public void populate(){
        for(Network n:system.getNetworkList()){
            DBoxNetwork.addItem(n);
        }
   }
    
    /**
     * 
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNetworkWQ = new javax.swing.JButton();
        btnProductWQ = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnManageAccounts = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DBoxNetwork = new javax.swing.JComboBox();

        btnNetworkWQ.setText("Network Work Queue");
        btnNetworkWQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkWQActionPerformed(evt);
            }
        });

        btnProductWQ.setText("Product Work Queue");
        btnProductWQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductWQActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdminRole/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnManageAccounts.setText("Manage Accounts");
        btnManageAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAccountsActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Network");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DBoxNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack)
                    .addComponent(btnProductWQ, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(btnManageAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNetworkWQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(DBoxNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnProductWQ, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNetworkWQ, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SysAdminWorkAreaJPanel sysAdminwjp = (SysAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnProductWQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductWQActionPerformed
        network = (Network)DBoxNetwork.getSelectedItem();
        SupplierOrganization org = network.getSupplierOrganization();
        ProductWorkQueuePanel productWorkQueuePanel = new ProductWorkQueuePanel(userProcessContainer, org,network, account);
        userProcessContainer.add("adminWorkQueuePanel", productWorkQueuePanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProductWQActionPerformed

    private void btnNetworkWQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkWQActionPerformed
        NetworkRequestPanel networkRequestPanel = new NetworkRequestPanel(userProcessContainer, system);
        userProcessContainer.add("networkRequestPanel", networkRequestPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNetworkWQActionPerformed

    private void btnManageAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAccountsActionPerformed
        
        network = (Network)DBoxNetwork.getSelectedItem();
        
        AddAccountPanel addAccountPanel = new AddAccountPanel(userProcessContainer, network);
        userProcessContainer.add("addAccountPanel", addAccountPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAccountsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DBoxNetwork;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageAccounts;
    private javax.swing.JButton btnNetworkWQ;
    private javax.swing.JButton btnProductWQ;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
