/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LabourEnterprise;
import Business.Labour.DeliveryPerson;
import Business.Labour.SkilledLabour;
import Business.Network.Network;
import Business.Organization.DeliveryLabourOrganization;
import Business.Organization.Organization;
import Business.Organization.SkilledLabourOrganization;
import Business.Organization.SupplierOrganization;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nitin
 */
public class ManageDeliveryPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryPersonJPanel
     */
    private JPanel userProcessContainer;
    private DeliveryLabourOrganization org;
    private Network network;

    ManageDeliveryPersonJPanel(JPanel userProcessContainer, DeliveryLabourOrganization deliveryOrganization, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org = deliveryOrganization;
        this.network = network;
        populate();
    }

    

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) tblDeliveryPerson.getModel();
        dtm.setRowCount(0);

        for (DeliveryPerson deliveryPerson : org.getDpd().getDeliveryPersonList()) {
            Object row[] = new Object[1];
            row[0] = deliveryPerson;
            //row[1] = skilledLabour;
            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeliveryPerson = new javax.swing.JTable();
        btnBonus = new javax.swing.JButton();
        btnNewDeliveryPerson = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblDeliveryPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        DELIVERY PERSON", "Total Items Delivered"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDeliveryPerson);

        btnBonus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdminRole/money-bag.png"))); // NOI18N
        btnBonus.setText("  Bonus");

        btnNewDeliveryPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdminRole/plus (1).png"))); // NOI18N
        btnNewDeliveryPerson.setText("  Add New Delivery Person");
        btnNewDeliveryPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDeliveryPersonActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdminRole/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNewDeliveryPerson)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBonus)))))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewDeliveryPerson))
                .addGap(191, 191, 191)
                .addComponent(btnBack)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SysAdminWorkAreaJPanel sysAdminwjp = (SysAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNewDeliveryPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDeliveryPersonActionPerformed
        // TODO add your handling code here:
        AddNewDeliveryPersonJPanel manageEmployeeJPanel = new AddNewDeliveryPersonJPanel(userProcessContainer, org, network);
        userProcessContainer.add("ClinicManageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNewDeliveryPersonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBonus;
    private javax.swing.JButton btnNewDeliveryPerson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDeliveryPerson;
    // End of variables declaration//GEN-END:variables
}
